# -*- coding: utf-8 -*-
"""PCA - Todos os ativos da B3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IUSDlNFBCjLUqsKTAKrEqGJaaeOsnl3I

#Bibliotecas
"""

import numpy as np
import pandas as pd
import scipy

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.preprocessing import StandardScaler

from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

"""#Importando os dados"""

df_segmentation = pd.read_excel('balanco-ativos-b3.xlsx', index_col = 0)

"""#Explorando os dados"""

df_segmentation.head()

df_segmentation.describe()

"""#Correlação estimada"""

df_segmentation.corr()

plt.figure(figsize = (22, 19))
s = sns.heatmap(df_segmentation.corr(),
               annot = True, 
               cmap = 'RdBu',
               vmin = -1, 
               vmax = 1)
s.set_yticklabels(s.get_yticklabels(), rotation = 0, fontsize = 12)
s.set_xticklabels(s.get_xticklabels(), rotation = 90, fontsize = 12)
plt.title('Correlation Heatmap')
plt.show()